# Generated by Django 4.2.2 on 2023-06-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skills', models.TextField()),
            ],
        ),
    ]
