# Generated by Django 4.2.2 on 2023-06-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_recommendcourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendCourses',
        ),
    ]
